### ISSUE TITLE
False error about footnote anchor placement

### ISSUE THREAD

**Issue by wf49670** [davem2/dp2ppgen#2]
Using this input file: https://dl.dropboxusercontent.com/u/3229599/cicerov2-orig2.txt
(different version of file from my first issue) I get the following error:

> CRITICAL: Anchor found on different scan page, anchor(374.png) and footnotes(372.png) may be out of sync

As far as I can see the footnotes on 372-374.png are fine.

This happens **only** if I have the -e option specified. With -pcfjs it works fine, but with -pcfjse the error shows up.

**Comment by davem2** [comment]
The section processing option (-e) does not work very well at the moment. It tends to mark things that are not sections and mark more lines than needed when a section is found. This is mostly due to the ambiguous way that sections are marked during formatting rounds. I have some ideas on limiting the amount of false positives, but I'm pretty sure this option will always have some degree of failure.

Section processing happens before footnote processing so I would guess that the problem here is a footnote is mistakenly picked up into a section and causing issues on the next pass when footnotes are processed.

You can get around this issue by running multiple passes on the file:

```
dp2ppgen cicerov2-orig2.txt cicerov2-orig2.txt -pcjfs
dp2ppgen cicerov2-orig2.txt cicerov2-orig2.txt -e
```

**Comment by wf49670** [comment]
On 3/16/2015 7:32 PM, davem2 wrote:

> The section processing option (-e) does not work very well at the 
> moment. It tends to mark things that are not sections and mark more 
> lines than needed when a section is found. This is mostly due to the 
> ambiguous way that sections are marked during formatting rounds. I 
> have some ideas on limiting the amount of false positives, but I'm 
> pretty sure this option will always have some degree of failure.
> 
> Section processing happens before footnote processing so I would guess 
> that the problem here is a footnote is mistakenly picked up into a 
> section and causing issues on the next pass when footnotes are processed.
> 
> You can get around this issue by running multiple passes on the file:
> 
> |dp2ppgen cicerov2-orig2.txt cicerov2-orig2.txt -pcjfs
> dp2ppgen cicerov2-orig2.txt cicerov2-orig2.txt -e
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/davem2/dp2ppgen/issues/2#issuecomment-81991383.
> 
> Yes, I can imagine programs would have problems given that a section is 
> signalled by 2 blank lines but may or may not have a header. I think 
> that GG may assume that anything longer than 2 (3?) lines is not a 
> header, but it's been a long time since I looked at that code.

Thanks for the bypass suggestion. And thanks for what looks like a very 
useful adjunct program for ppgen. It found a number of 
proofing/formatting errors that might have been tricky to spot easily, 
in only a half-dozen or so runs.

Regards,
Walt

**Comment by wf49670** [comment]
On 3/16/2015 7:32 PM, davem2 wrote:

> The section processing option (-e) does not work very well at the 
> moment. It tends to mark things that are not sections and mark more 
> lines than needed when a section is found. This is mostly due to the 
> ambiguous way that sections are marked during formatting rounds. I 
> have some ideas on limiting the amount of false positives, but I'm 
> pretty sure this option will always have some degree of failure.
> 
> Section processing happens before footnote processing so I would guess 
> that the problem here is a footnote is mistakenly picked up into a 
> section and causing issues on the next pass when footnotes are processed.
> 
> You can get around this issue by running multiple passes on the file:
> 
> |dp2ppgen cicerov2-orig2.txt cicerov2-orig2.txt -pcjfs
> dp2ppgen cicerov2-orig2.txt cicerov2-orig2.txt -e
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/davem2/dp2ppgen/issues/2#issuecomment-81991383.
> 
> Footnote 2 at the bottom of 372.png has 2 blank lines before it, which 
> would likely trigger the problem you suggested. I removed one of them 
> and reran with -pcfpse and it ran further, until it hit a Python stack 
> fault.
> INFO: Saving output to 'cicerov2-1-src.txt'
> Traceback (most recent call last):
>   File "C:\Python34\Scripts\dp2ppgen-script.py", line 9, in <module>
>     load_entry_point('dp2ppgen==0.1.1', 'console_scripts', 'dp2ppgen')()
>   File "C:\Python34\lib\site-packages\dp2ppgen\dp2ppgen.py", line 
> 1665, in main
>     f.write(line+'\n')
>   File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\x97' in 
> position 49: character maps to <undefined>

I'm going to refresh the file on Dropbox as I may have made some other 
changes to it.
   https://dl.dropboxusercontent.com/u/3229599/cicerov2-orig2.txt

It might be nice to trap that kind of error and identify where it 
happened, as it's friendlier to the user :)

(By the way, I know what happened. Many of the em-dashes are coded as & 
#8212; (without the space) rather than the actual em-dash character, and 
sometimes the project text file even has & #8212;- instead of --. Sigh.  
Of course, it is a very old project, before the split between P/F, and 
so may have more proofing flaws than we'd expect today. Anyway, I 
converted them to real em-dashes, but neglected to switch the source 
file encoding to UTF-8 first, so they really are invalid characters. I 
was able to determine this by looking at the output file and seeing 
where it stopped.)

Again, thanks,
Walt

**Comment by davem2** [comment]
> I think that GG may assume that anything longer than 2 (3?) lines is not a header, but it's been a long time since I looked at that code.

This is how I was planning on handling it (with the max line parameter configurable). 

Glad you are finding the program useful, it's saved me a lot of time PPing (well, I probably spent that time and more working on this, but that's another matter : ).
